source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.3'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.1.4', '>= 6.1.4.3'
# Use mysql as the database for Active Record
gem 'mysql2', '~> 0.5'
# Use Puma as the app server
gem 'puma', '~> 5.0'
# Use SCSS for stylesheets
gem 'sass-rails', '>= 6'
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'webpacker', '~> 5.0'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false


# sentry
gem "sentry-ruby"
gem "sentry-rails"

# job schedulers
gem 'sidekiq'
gem 'sidekiq-failures'
gem 'sidekiq-history'
gem 'sidekiq-statistic'
# END job schedulers

# HTTP client
gem 'faraday'
gem 'faraday_middleware'
# END HTTP client

# shrine
gem 'shrine', '~> 3.0'
gem 'aws-sdk-s3', '~> 1.14' # for AWS S3 storage
gem 'mime-types', require: 'mime/types/full'
# gem 'image_processing'
# gem 'mini_magick'
# END shrine

# ActiveRecord Expansion
gem 'sorcery'
gem 'enum_help'
gem 'ancestry'
gem 'activerecord-import'
gem 'discard', '~> 1.2'
gem 'deep_cloneable'

# i18n
gem 'rails-i18n'

# crontab
gem 'whenever', require: false

# error page
gem 'rambulance'

# Bot measures
gem 'recaptcha'

# pagenation
# gem 'kaminari'
# gem 'bootstrap4-kaminari-views'

# other
# gem 'cocoon'
# gem 'romaji'
# gem 'liquid'


group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 4.1.0'
  # Display performance information such as SQL time and flame graphs for each request in your browser.
  # Can be configured to work on production as well see: https://github.com/MiniProfiler/rack-mini-profiler/blob/master/README.md
  gem 'rack-mini-profiler', '~> 2.0'
  gem 'listen', '~> 3.3'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 3.26'
  gem 'selenium-webdriver'
  # Easy installation and use of web drivers to run system tests with browsers
  gem 'webdrivers'
end

group :development, :test do
  gem 'pry-rails'
  gem 'pry-doc'
  gem 'pry-byebug'
  gem 'pry-stack_explorer'
end

# gem "tailwindcss-rails", "~> 2.0"
